import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import CommonLayout from "@/components/common-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "User Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonLayout>{children}</CommonLayout>
        <Toaster />
        </body>
    </html>
  );
}
